apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - traefik.rbac.yaml
  - traefik.pvc.yaml
  - traefik.yaml
  - authelia.middleware.yaml
  - authentik.middleware.yaml
  - dashboard.service.yaml
  - dashboard.ingress.yaml
