apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - prometheus
  - authentik
  - authelia
  - dysautonomia-web
  - jpat-web
  - kutt
  - lacework
  - lemonhope
  - nocodb
  - plausible
  - serubin-net
  - vaultwarden
  - weave-gitops
  - whoami
