apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/prometheus
  - authentik
  - authelia
  - dysautonomia-web
  - jpat-web
  - kutt
  - lacework
  - lemonhope
  - plausible
  - serubin-net
#  - tandoor
  - vaultwarden
  - weave-gitops
  - whoami
