apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aj4democracy-ingress
  namespace: default
spec:
  rules:
    - host: ${SECRET_DOMAIN_HJP_ORG}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: aj4democracy
                port:
                  name: web
