apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/authentik
  - authentik.sops.yaml
patches:
  - path: postgres.hr.yaml
    target:
      kind: HelmRelease
      name: authentik-postgresql-cnpg
  - path: authentik.hr.yaml
    target:
      kind: HelmRelease
      name: authentik

