apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: cloudnativepg-charts
  namespace: default
spec:
  interval: 30m
  url: https://cloudnative-pg.io/charts/
  timeout: 2m
