apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - authentik.chart.yaml
  - authelia.chart.yaml
  - bitnami.chart.yaml
  - bjw-s.chart.yaml
  - christianhuth.chart.yaml
  - cloudnativepg.chart.yaml
  - cloudpirates.chart.yaml
  - kyverno.chart.yaml
  - lacework.chart.yaml
  - longhorn.chart.yaml
  - minio.chart.yaml
  - pascaliske.chart.yaml
  - prometheus.chart.yaml
  - vaultwarden.chart.yaml
  - weave.chart.yaml
  - zekker6.chart.yaml
