apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/prometheus
patches:
  - path: prometheus.hr.yaml
    target:
      kind: HelmRelease
      name: kube-prometheus-stack
