apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/nocodb
  - nocodb.sops.yaml
patches:
  - path: nocodb.hr.yaml
    target:
      kind: HelmRelease
      name: nocodb
  - path: postgres.hr.yaml
    target:
      kind: HelmRelease
      name: nocodb-postgresql-cnpg
