apiVersion: v1
kind: Secret
metadata:
    name: grafana-auth-secrets
    namespace: default
type: Opaque
stringData:
    grafana-client-secret: ENC[AES256_GCM,data:mcODF1L2nSm0YEo4K7Ez1YMuY0rSI2MXuMzpF8sOoYiNVq/EGG0u4TPmWiXcVNsWM1Ivneto9zvacURfAU/hcHIBT5581iGfm5HGDWfmeZMG8KUvCiqHGA==,iv:HGSL4aa2HQxjWXilD6neUdXpIL9BwiMfR3+96Q+bNCo=,tag:VegOy78mCei2p7hYS3pMxw==,type:str]
sops:
    lastmodified: "2026-01-02T02:29:00Z"
    mac: ENC[AES256_GCM,data:AFX9rFtddfMGanLX5S5bDUJ4vpHo6plvPWMndflLKdXi8vYJCYCQurbCkaLp+054q+YCPDA7AW9aPzqgHbZqcfH6+HHyQlP9kStmUx+wKCUe+xVYGAfeQ4zvcwTlKyCyWLjgXUZ1kEA68xh7p9S8cL3Wz3QFTAE+6gX/VRd7vKE=,iv:l0a8FmDerSnD69x7fXevQKZi7+1m+ZjhzO5aP8qdVww=,tag:Wq+WEezONEG9iKI11KHTVg==,type:str]
    pgp:
        - created_at: "2026-01-02T02:28:47Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0i7SvTnDueaAQ/+PL4faUWAee7NHU5rlGK1Dce6ei9mjWyIK3IKhD4zoxhK
            QskeaRV/U+wDjvqHGCDNbZYwu98CCpeeAtSJ24YVADIwrCxDO9W/VwyINX/eEcyR
            Rm/wxIZrrW6rMuStxs6lvKP+R8hGPdFFlrR5f5X8cjSDMrGcK2f+OjU3y25yc2m8
            tMBfAu0kFyKyfkIw3z60uHBafequr+D6yCJnqcw5Wl6Ck/ikK+siHekC72RtqELp
            fN9iKDuFU6Xj5d28mGobo5fEsQnxkUeDihiO3sBRcTsckEAK4gi/Z38KquSeeYgs
            /z3ZPwLH48K3lHPf/IpONVBF4VemTFflHj5XrvE/9CMVkqn3WX+VXqRG6FEj85r0
            cN/TkjTJaF1jnfrXz2aKfQrKufILG+KPsbmv61GfOaKkuhgRAiFNaMKcxodhMuIP
            1aVNppTLmrGVEvdS5EfBxzmBJFWZxvMog7NaYJeaSHcYLBHcz1RTIfdU4HiAAXqi
            DAcmn2HF8Bz7XFve7/5NiD3oAkgatEpqllvFsFomIRXr5Oacdf1nXNVVBRYKYn9m
            Edjs3Hv3wuQS3ZVze/jWlmFdaivnO1+EA+FVFws660Ve6e3QxswqtGvNmQIwyqjk
            lbo5rhaUADfix1x1cWzyU+x9aw1+QNiOagU4tX9qtHbbzfa+GJEmqKCJSPG3f6vS
            XgGuoYX36tBAm0Zex6KREhO8xpbVWnhKsd/+D68I6WLVrxWwT8MyV3CRWtwYcwWB
            r9/VBlE6bFu4HVwVTd5thShNEc6l6/3J2SYh0OecJ2Oj4APcsuW3xE0uFJTkX+o=
            =xAEv
            -----END PGP MESSAGE-----
          fp: 7EB1A78D86B11352982D3A1F7037153C2DB9CDBD
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
