apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - grafana.blueprint.yaml
  - grafana-auth.sops.yaml
patches:
  - path: authentik-grafana.hr.yaml
    target:
      kind: HelmRelease
      name: authentik