apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    CLUSTER_HOST: ENC[AES256_GCM,data:D0/jcK+De3Fc3kZ6LdfGnqZ92/kVSG+2D2jD,iv:kt3GpPlQOw9+hp1OYVx1kcIxx3Gl2LnEOr0dZf6rB40=,tag:r36P/I0oGVI4tfOnLtiXDw==,type:str]
    BASE_HOST: ENC[AES256_GCM,data:Bh9fs7fgTI3/0Wg=,iv:GjoQKnJvZbGPmO+Aua/jLdXA4av30XPTgAICJF35HPQ=,tag:twgddvYAAeVt9jOMvoG9zw==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:TzcuzqiuLZLo6R1DyPc03SOvwA==,iv:bIhZPPhTqqPgpF/yAe+W5P77dSWdlvwUHaROC8tCq7Q=,tag:8OFM5IQDyrU8/KF5tfMr8Q==,type:str]
    EMAIL: ENC[AES256_GCM,data:Kgb8P+OFT0F1uX7JNMINPoUv4g==,iv:IFBR6s9boGD4fJd9FYfyjrgOYEI1CWUtfe35+DHCYhA=,tag:w6kuaJBuqfNEVTAxbzBBYQ==,type:str]
    ADMIN_USERNAME: ENC[AES256_GCM,data:OO5IK9h0Nw==,iv:qqNCOrktJLZSX4313qSBwe1QNmUy0o8zdq7Gkk4g5Uo=,tag:fY3aANJBcjHtpYQQyMsV3Q==,type:str]
    ADMIN_EMAIL: ENC[AES256_GCM,data:tOqQg6G3wDmq6dXyw6hFP74=,iv:V/YVsfChhj2OqR9IeF7ZqaNOIauPoWXRbboMPJkvOeA=,tag:sv+ewCYTCaib6p8OAkkrYw==,type:str]
    #ENC[AES256_GCM,data:02xfynKYh2JK,iv:lWUB5ynFVpE5i5Jv5eqf0Ra96SG3vH7VlLh2irtlbwo=,tag:j2wJn9e+aCOyXM/EKg7GZA==,type:comment]
    NOREPLY_SEND_EMAIL: ENC[AES256_GCM,data:Ur3KsgOkp9P4pY3SNOGUFmap3HZsWQB3,iv:AkVefYrdlzxyIEvqBN62jEyXValsUQ/q0H/ptbHNRiw=,tag:Ll0vAsR+FrDvID7U9VwmrA==,type:str]
    NOREPLY_AUTH_EMAIL: ENC[AES256_GCM,data:+1WtfvcZzrUkgXeD2i4bjmFhqQ==,iv:HwXxQiQD+fg+sXBRDgoLbejDxWLkAR0kcxcUuXUnzPQ=,tag:dC/1I6OWAulTZYKWeEqjog==,type:str]
    NOREPLY_PASSWORD: ENC[AES256_GCM,data:etbLKF9cF8n+RvmcoyvdbZ5jbg==,iv:Ce9XXwX0hP0MTFudBBwWjj+Qpg2r+/zOKXbH+bUSXgY=,tag:dfhntnVhRJHiQpLyWrXpMQ==,type:str]
    #ENC[AES256_GCM,data:iemw+IJm4n2dJtTl,iv:+D8mm7/a7CrhAUVNQUOMHrAdj86eHnxch0EutY41r1w=,tag:uw3eEsMMp9yZlO8MdH071g==,type:comment]
    YUBICO_CLIENT_ID: ENC[AES256_GCM,data:PHPCtaY=,iv:N6kVwY/p4YKo7pA9rWjHgq9ZZxp0pl66ArUo7p7DBVc=,tag:n+OB62luYGQWQ3MXHvnV1w==,type:str]
    YUBICO_SECRET_KEY: ENC[AES256_GCM,data:jTFcJxxIkOh0Z3noK8S/IVdoj3MjKvDMJlVCeg==,iv:BYqbhvx1L2wZhiJRO0AsNc1y/d9KjMGIJWwazAxXScg=,tag:jIkfLa0GGt3kGC3P8lWVHA==,type:str]
    #ENC[AES256_GCM,data:2hhrgBbHEgn/JA==,iv:w1PuGjogQO5Zkbl6y2H/rV7Bxz1Ie/zDuifmXNux7h0=,tag:bUdC71lJQ+/dAP6Vuom8DA==,type:comment]
    TANDOOR_DB_PASSWORD: ENC[AES256_GCM,data:xoTMqTWivEslJ2Rd7PjYzm8B18xKJZivysXgc7Oz6BETY9pUB1satm3BVnacoRu4iqeP9Q7bnj+5uB1gGR5fEA==,iv:isT6j0jljcZQ55vCfz9KgYFz2HoBD2AtZhmVDxiujl4=,tag:fk8/2EAFFss7D+zLHiL/fw==,type:str]
    #ENC[AES256_GCM,data:DuN5Kb4=,iv:MgDAo48hEJbvo2YeQdjahF7h7PUL2QGm8Uowuvif9CI=,tag:Jy+dc9UKsMjMkJzUaRRiAQ==,type:comment]
    KUTT_REDIS_PASSWORD: ENC[AES256_GCM,data:R2pahby3w1jhQCpFhVrJcKvN/M8WL7hN6jH5PveVrBHBrz9JR7eNoE+wBH9YLNZ2nBcH3KpFQdvzuKCIfCuYGQ==,iv:mx33XmpI/G8eLcfAaz8deL2NlClmYxcVbwqDDjPy4mI=,tag:xs0r5XTsztH0Ra/FKKDLbw==,type:str]
    #ENC[AES256_GCM,data:m+FHCBIJkm9d5qDd+g==,iv:i9E6DaZXhKgjfXw4yY7uxS8nxc1tFhI9e9KID4QIjnA=,tag:o6T8LtICtQ1bSbQ0Wqx82w==,type:comment]
    OIDC_GRAFANA_CLIENT_DIGEST: ENC[AES256_GCM,data:o4AxazdI06sVNmIyZwsW6RFdJC0hw3YlfYtAvf7YIEgm6gYm9eTBa+8UgTTeqIja34KCAtj+JGpvJldZczMZkrUJuZuLYrnF+ADaMeYMUz1jyerKc56fz6KpBYlLUUlmVYqzLzmnF1qvKtVmNeA6tu0CQTQmAZFKE/fBbSdgFbhDqfc=,iv:wajfP/CKUvPuuHZGr9fmoWqAgp/Y2saelttVry7MMfg=,tag:86rLxgch+4SOo1AmAJSfPw==,type:str]
    OIDC_GRAFANA_CLIENT_SECRET: ENC[AES256_GCM,data:vD2vMjeLJHGkcJtZyTk0u1AEkn7Jyejd7ZXKv/aRqITTgjq/mwpOykPVh7RpaphPbWD9yvPFXZJnWhHXq19xvTJagx1HaBmOWWMjkVipyxGbWDotHb9LfLZuWdmrWH7GX6badvduwElB/YgNpnv4MuvWIZUpIGzYeW8Oy3FcHEk=,iv:1udGrvbliIMug9Xp2VU7ws3PLmG8Mn/wCq4IdxQ8HTI=,tag:qVYHS3wFnIfBzlAiZSMi3A==,type:str]
    #ENC[AES256_GCM,data:JIKdBoKcjMFL,iv:Oa4QGoTRLx/M0DZ6UNbeJl8B3nuO2AtmA791Nvq/9QI=,tag:V6T3dn54lr9NnhBHwZg3bQ==,type:comment]
    LONGHORN_BACKUP_TARGET: ENC[AES256_GCM,data:2+n4SxZ6qzQkT9gzk8ys5WM9NZehR96hxlGz5fyLez9W47WpRnThMCxv,iv:+naWZtK+TmhfvxoOCckIakumKqireYGOXntsi4etGdw=,tag:srz0zqnKbnWIK4wr+xliPA==,type:str]
sops:
    lastmodified: "2026-02-22T23:00:10Z"
    mac: ENC[AES256_GCM,data:2V87LWVFMMzyiH/veR4kD1mGNkBwjPxrJg3jZuRRJCPRaw+OMRkA3T8PJzPPZe2E+E0pJD2kqnPWSURFQqARR/lz451Y0orMvQDI679NIVS7ruYY0kXSeZxhS0xt7qUcHLK3adLcYkzzFwQW+haqxt8Xchs14vLw4Zib/ku2nqo=,iv:rqXatTm1JHVrKwOAjU7M0C75zYwbDoAhhYmnrSAOwNk=,tag:G90LNBhmCRsgUJWcL3p13g==,type:str]
    pgp:
        - created_at: "2025-12-10T00:36:44Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0i7SvTnDueaAQ//YP7d7xLMpyxRH7l0IwdaMteToHUQZJRCsnQSX5qqxfRA
            2MrtM3mzUUfvsfWlrsbJOhctMevKtUP/cVlQ29NmbyWgYrKT23TmQTWW9D0PV4Vd
            pNRALPrjFiI0/Z5oO5Hv0ImIHjwHGM8HBnO6Ta//T8GUDkajF6XvlqBvQeviMB+C
            uWnJDDqPxMe1jGDLowRYhwe+U5GAhbEyTozY3L/uz8W2/ECZgSNWrZOkndh4ZLM1
            7p7ZoaTz1eCkJvcIWC3aGGgYvCyztoZ4Z0xcZWcXYhIaFtN6OSJKyKMCdHsyZo8s
            KUqZcGst+gTVbculc+bwoVcJW+e6seNPHVEoRpC/ngs7OlnuGpt14pWJoePUT5KK
            nCyU2ZqV+YVt2sNx0Sb2ANfk9YDsRaJxZJQuKnVpCcSlwvOG2cif0ISocgRuU3tG
            AgflTy7AQXJQfHfuCl3kge0WE3Ww4bW5qpf2Sk1oUbEUsLEyZvpHJy8PVOAAWalp
            picl9t2O1KTqPpLcroCSVN8D0Fr82SSrIyiYrXfqu3TUA+WQC5jFRq7tRq5OQ7JC
            yD/mEsOShWGRtNh/2+w6zGeqmr2JXS6d0UAcw5ZPL46rgwxT+UK3NFFWCZr7Mzgx
            uwL4nK7H7UKKfCPMtOLV+6uJN5/gbWgRgpNUB/Q0vjmJLOplAyllEjocMbjoYKjS
            XAGL+9aapPMIOmzP066oSMnmHl8CGslEum/e7JPt/QMg2NUegWtwrKmyDoBombOg
            i9LFLiqqArMn2unQLlfyI/10MuI692QQ4cC1J01dmZAaloALk6qpOuDbj4Lj
            =xQr4
            -----END PGP MESSAGE-----
          fp: 7EB1A78D86B11352982D3A1F7037153C2DB9CDBD
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
