apiVersion: v1
kind: Secret
metadata:
    name: longhorn-backup-secret
    namespace: longhorn-system
stringData:
    #ENC[AES256_GCM,data:iC2rU+FZUCAeKFOmMHES5//vzIL/rwSCQeOU2tzPa4FI1ikUnNGlh+7gu+hY,iv:ZL774Dc4gIuxCWeS2g0QmKtfV8b5KnUIvPggmxreg3I=,tag:1ztCTLI81AP6NCiwd+Aodg==,type:comment]
    #ENC[AES256_GCM,data:AOHtesqIowgeA30ccynsblSF1r3TZ7bYhrrOtX0noHLBtiGKgzSpafMWs3A9hXt3adciwN5OhehRUZ/dEsgMrA==,iv:Shd2ZtgqUYueTB356STgKCtMFlSo82KrGqnIIvUGhMU=,tag:1xBTmGm53+qpLzqGtsTrEw==,type:comment]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:XMKTKdd+u4DU0tDtB1NPBhtpp1ghuJAqaqc/bw==,iv:6vODzXxDrk0NQ4ArKCf87vY/qVi4KXSI0gYZUFXObI4=,tag:5LG9//7WxUM6x5WlTRkTNA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Z2Nx42Z+uuHcTXMKotDB3bv+SFqbUDX+7w==,iv:gTCaqBli8xDkWJWtvAPHswVzUuozwZz5lc7dQLmqVKM=,tag:y47XeAbIa3uo1fcFFOEbTQ==,type:str]
    #ENC[AES256_GCM,data:XtGrdUb44r7bVOBBbYTQvav2+tqPfi1Ai6bbSInuQ8kvo8NwdMKM4qyze1ZliLs=,iv:TySAnpdCnOHCcoLODTQfKm6LUhVRSXuLHoAsnBWEbIg=,tag:8E7W4JHv1BBGcU+kY/cjaQ==,type:comment]
    #ENC[AES256_GCM,data:KPI1v4VrtcxEizD0N6adTriFVtarpu17aHj82NGk7izueDG6gN01nNBjR0E=,iv:gEr1irvdxFgNZ6UtI6AIjj68E9mDr9px92SvrvnyFVc=,tag:oNEI5lvqxS6urn1bTX9NPA==,type:comment]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:uisb2rpZom7XEk//AmQWze2FAeAGt2So4vUs+cECH5L9xFGaVuOPuA==,iv:5sgZ9GGbZBFsXC+WGcFHaYD7/QehyJuXbsW8bANpHG0=,tag:n+iMjoN8lWL0Z/SA1ovYSA==,type:str]
sops:
    lastmodified: "2025-12-29T00:06:56Z"
    mac: ENC[AES256_GCM,data:XjYrvjj4Lk41FkJVUEirn3uTiq0euKlDOrmJ9vYJ0M/FdSqOUAeiPgz3Lx6a6KJ6711wM+9kkTVZgHd16KhaaQZ0TcVQ1nR+RWPfzVBEpFXIVMZSgRGmXarP2pn240Rucp6N7xTZggEbICH0g09MVGBTJ0yAssnKbsVtBFNJVWE=,iv:UcCoup/G7PqLHDRpEJ4kKhghduDsmA3+x/zQnTBV6XI=,tag:hNqHzAJNpdjwdUJpYuGxIA==,type:str]
    pgp:
        - created_at: "2025-12-29T00:06:56Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0i7SvTnDueaAQ//RPtQV03jeRa5YuLtTg7Dz0YtITJW07bz+1NW5BOWff7v
            DeMDnoULI4QCqsCGfjxF8y1t6FfTTIWbI938Rzp4Nb5YnN0NbQh+a4iT+S7L6EKC
            RejuAMLUwadKsn0ujI+rBhAbOmTlH17wn1dnHC/vEtkNz7Z+VOYgfhv3GAFtKM1K
            iNirlQ2hBLP0RCUR41KkQOiSfpF1mRt8JfcPFzDxDkMB9+gsSny77G7LwrQSoKVd
            7zF44+8SWoOQ+SZul07YImKM1lEcJa0KX6QOSxWCXq85RaYrkFHx315QyAS+tVCm
            uyIRpC1Ex72jOn/4CBa/ZVn8MPKx8WRmd5aa2BoG7iMcVvOEuSqFxjIUdRSSb2qj
            CXAHuCsGW2psRp8u6TwEO8Z7YMt17Xdz4ajm4UYhCOWCB3yOjT3P7d24NLtsa0YA
            gcPQwhuixximY3IVrZ84RWcn1E6NgMDpebNufIXcqauSfs5ed0w5uQLpu3rjsOVr
            QgmyxUDcrJ8wMm3ZgoDAOOVVeiMyXluJSZG9kQjNaNSBKI9US3fWOtNdJywNS5sb
            EU+e9gRHooWAnxBoTLwDXgag1QrlKWVH1KlkTQHCQN91uNUb+876oB4ylrGGSvVU
            yVDOxpwB966nyMoGwlqMAY1/ddW0OXcTNN1Nk74Ce67+wEM39KWHE8okLPRRsjvS
            XgE1olmvKuhoPcNW39kORaqmRXxK55AuB6LZhcl4J/vsFhknXS8zc+j9bPuBtlFm
            t9YHbTAxyFKtXR1u88Oew7gOtIMEQmYwnrs67HV8gxlVuGUKXyDnAvAI2rLr4tk=
            =ohJ/
            -----END PGP MESSAGE-----
          fp: 7EB1A78D86B11352982D3A1F7037153C2DB9CDBD
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
