apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/plausible
  - plausible.sops.yaml
patches:
  - path: clickhouse.hr.yaml
    target:
      kind: HelmRelease
      name: plausible-clickhouse
  - path: plausible.hr.yaml
    target:
      kind: HelmRelease
      name: plausible

