apiVersion: v1
kind: Secret
metadata:
    name: grafana-secrets
stringData:
    admin-user: ENC[AES256_GCM,data:T3Pom+ur/AfYeMt9yg==,iv:S1nMtJBoVcdSpAhfImJsg5eJHSeOb/pDiLccyUWZ11E=,tag:QqZMkGS3tVhasoIQ6rEoww==,type:str]
    admin-password: ENC[AES256_GCM,data:QlT84QLr40aHfqektquBkMRV6vgMBumtW1R35l1EpHyL71akZL/chOP7IHGLz/5qQsBWWs/BBSPfRfKrZCNSMw==,iv:Y5EvzChA4ULej0Ecsjm9aPLFyt0+zOrPkY+kcS5RlK0=,tag:bo2qlaHZh3DINKEBPYPd1Q==,type:str]
sops:
    lastmodified: "2025-12-10T00:36:59Z"
    mac: ENC[AES256_GCM,data:l2MffytJ4txjVp5xyh4k/sZHzgomE93Yi0HtYPp+bwsEKvsX0iA6QoN6gm5HIPavQoGhYctTQD91VJSvAgKHdvpflNoOoW6sv4F+jM2UDx29NXnYt7nzItkLzHwdtXuMPPEju9xeuW8tRPninDNCiR6WnAGHgryClOxKkwj3/Z8=,iv:gBnccaeuWgTdN4yBRMRx+lakBdNMLlDHEPP8K11Gkww=,tag:iqVauxxjImr06U34TaFoZw==,type:str]
    pgp:
        - created_at: "2025-12-10T00:36:45Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0i7SvTnDueaAQ//X2E4iCV0sRVkpxf41wH0cJiSyoun+2b4ZdIppvYI/uSc
            sRFPjtNjdGrGjnOpkU+xj60V6knY4uhpu6qSfYtEd9LfwjNx2wcGzyq1mu5cgb0e
            topVO/8y2SJZCFPtAn29qu2GAceKos3Yc6faCp5kLlaK7alaaXe971mYCJNBHVFr
            M+T2y1MzIbFpOGl7SPOE2PQN4EHb0emrs+Vy42ZuwDM813HswrOHhWMsRA9IxaUq
            YP7LPyekarHkkCBs/ZpxkkFwi2rG8+GhQSjeHX9zawqRjlO8+gx45wLq/v9+oPSd
            dqwgNTG9Xzbnu/fVjszMfduL/HjYW58FcmIEVdb+DLw1L13XCXuDfJ3S0sUirwKs
            qnDB9/i6ONEhQ6ANk2BTRvDE/6RhGGfFWD5/9rf68QwYC9gjqXE47K64eSHapO5k
            Gy0ctHR4WtIxmwb5J98MDyfiRkcIMTzQHm/4gL9L7qkPLtNvJgMhDykG3RHSnxkz
            1Foxi5ekOcddeIo41DI1C5QBuzmBIF7jZ5Su7rJ1V/Zx9/tRVKNdSjC/oQHQvev6
            a61ChQwI/XgVcEM6BG51P6lOifbuVfDSx1H2z0IwWcYv4w/qUMel6mG3GH0ue79C
            IUnBQWUt9NWGX0R8ftXm1ufbk3tmQgkl+0rsJV43m76x544t8q2jk/LX3kByFEHS
            XAEbx1P3kBoqV3zJbFOYIYf9Wen/hGW7fSh+rnqiyWv3DtyXwM77p9nuPhQceev2
            qCQDAGVcWVglEyzFN/YjrGahnWDsh3DAn2NN8vC1EuWZcQw9z0eN12/4LSfF
            =Mzh7
            -----END PGP MESSAGE-----
          fp: 7EB1A78D86B11352982D3A1F7037153C2DB9CDBD
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
