apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    #ENC[AES256_GCM,data:c8fS/KSszLQ=,iv:SMXjqq6aG+BR3ELeRB8aeeVzRhsNGJ6Ml3SAKr/+5uQ=,tag:nfajcpX1wRoIRP4jWI7aNQ==,type:comment]
    CLUSTER_HOST: ENC[AES256_GCM,data:O/u++PoeW9VAJBf7EOkMnHEEA/PZxtOz,iv:9Wgnt0Fvkc71Nedie0b/3dkVgArJS9dCVb6WK89QQdM=,tag:VsA7Z/FrSC8nEplmDX8mRw==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:7xxMx5o8eGOMJm8=,iv:1Woa25GUqfMcZjCPwnkseC0q2hoFI0ircnHsIEwyH3w=,tag:wm+9DsXBITvDbx0l7pZ1zQ==,type:str]
    SECRET_DOMAIN_HJP_ORG: ENC[AES256_GCM,data:FAKHI8qdx0yNW0RbOuxjsw==,iv:hBuvC/4ockgckSo88DbsmUNwmBZFyD7b+pXQ6C7Zq1c=,tag:lAkBY1xk+IdV2EXp/Kytuw==,type:str]
    SECRET_DOMAIN_HJP_COM: ENC[AES256_GCM,data:KowLFspLEYTBQLzBNeGASA==,iv:9lHPRIETpN1GVCfmbpM4qWnq6+aMdpdKexTNWcitKIg=,tag:WFJtsRrgYpcXtEfzkdpW/w==,type:str]
    SECRET_DOMAIN_HJP_US: ENC[AES256_GCM,data:RIdEmcURbg==,iv:ZwMNNpv8v3JxaXvLF1j31SBiCZrt+f1DXhKVePRbzLA=,tag:gEGZofglFqniF6jo28H0+Q==,type:str]
    #ENC[AES256_GCM,data:GxkE4bIHyojg,iv:ZqcX/RtDKvN7d+njRvuGtUr1A2SzNwu23U92Sz4UFNY=,tag:YHJlrsZw0V/ezLhKMTJfgg==,type:comment]
    EMAIL: ENC[AES256_GCM,data:YzQeKG7JA+N5BAClECfEiM26JQ==,iv:IFBR6s9boGD4fJd9FYfyjrgOYEI1CWUtfe35+DHCYhA=,tag:caVp8/Cbk0q1zd/O7GkdIQ==,type:str]
    ADMIN_USERNAME: ENC[AES256_GCM,data:bzarstRymw==,iv:qqNCOrktJLZSX4313qSBwe1QNmUy0o8zdq7Gkk4g5Uo=,tag:NncQnCPpKHo6FP+dPhvI0w==,type:str]
    ADMIN_EMAIL: ENC[AES256_GCM,data:bryWk4mCVl24K3IkFkkrFVI=,iv:V/YVsfChhj2OqR9IeF7ZqaNOIauPoWXRbboMPJkvOeA=,tag:3/Uq/dzi1RANdMbCxQr5zg==,type:str]
    #ENC[AES256_GCM,data:yz4JzSIk05et,iv:lWUB5ynFVpE5i5Jv5eqf0Ra96SG3vH7VlLh2irtlbwo=,tag:d2cbS7xyi++bfzJoCzp1OQ==,type:comment]
    NOREPLY_SEND_EMAIL: ENC[AES256_GCM,data:Q/dvNouhY1lgroBvcFmnwywmpDPuLfsh,iv:AkVefYrdlzxyIEvqBN62jEyXValsUQ/q0H/ptbHNRiw=,tag:9f9F43SxKlSdkxbt08nAIg==,type:str]
    NOREPLY_AUTH_EMAIL: ENC[AES256_GCM,data:+BNJQrASjBNmQeY/E/GfmlTX8A==,iv:HwXxQiQD+fg+sXBRDgoLbejDxWLkAR0kcxcUuXUnzPQ=,tag:+lZ0l4BO3k899dDQIODZzg==,type:str]
    NOREPLY_PASSWORD: ENC[AES256_GCM,data:ud769S7xVHIgIS2+8Awl2KxZdA==,iv:Ce9XXwX0hP0MTFudBBwWjj+Qpg2r+/zOKXbH+bUSXgY=,tag:1LnvbNR/8XNhy8+hpLc5zA==,type:str]
    NOREPLY_HOST: ENC[AES256_GCM,data:+uDrzXUTgFixGdVV3Mo=,iv:pVsRyVB5oWNpiLJFYKAlGNbZZX+wz1ALG8rIKBmN+ks=,tag:X7n3rQfK+UA07tbj/SkjOA==,type:str]
    #ENC[AES256_GCM,data:89zbX3DunJKTEEKa,iv:+D8mm7/a7CrhAUVNQUOMHrAdj86eHnxch0EutY41r1w=,tag:QV4Min7IKe+4RrF7mzrrJw==,type:comment]
    YUBICO_CLIENT_ID: ENC[AES256_GCM,data:I0gKIPQ=,iv:N6kVwY/p4YKo7pA9rWjHgq9ZZxp0pl66ArUo7p7DBVc=,tag:oZJgJuWhHbXYxIE2eVkiPA==,type:str]
    YUBICO_SECRET_KEY: ENC[AES256_GCM,data:JCzY5Mw4xgOJClcbiplnDmU2ICSVSNOlXoNsGQ==,iv:BYqbhvx1L2wZhiJRO0AsNc1y/d9KjMGIJWwazAxXScg=,tag:mwXXbVW50QYIGnWRUP7/kg==,type:str]
    #ENC[AES256_GCM,data:Urw8Y1g=,iv:MgDAo48hEJbvo2YeQdjahF7h7PUL2QGm8Uowuvif9CI=,tag:ap+KJiFtWVGASAQTLn0ZJA==,type:comment]
    KUTT_REDIS_PASSWORD: ENC[AES256_GCM,data:9s2C/BqIVYdBN3ORWqS0DdLUPSyOYskmFL3oMl7st+HDcjfzz34pWZ0NEXwXYYQmADUW2rY1QPA4WyV5HCe60Q==,iv:891bLQtiP6/so/GD5MwiAF2BX0Ah//VHhS11P5MkRRE=,tag:MUje/aLmNYfoV5TPciKOgg==,type:str]
    #ENC[AES256_GCM,data:ZbCRqar9YoRcyLkxOg==,iv:i9E6DaZXhKgjfXw4yY7uxS8nxc1tFhI9e9KID4QIjnA=,tag:IZL44jhrTEV1zuOsz1eCWQ==,type:comment]
    OIDC_GRAFANA_CLIENT_DIGEST: ENC[AES256_GCM,data:UM2odgkRbSpw/NeEM2dgKWOW+k4JARjtx1LGanYSOq9FeMRx32vr9LGqC/MsRmI1VwEH2vTBO0x8eI8B2T4LNqgYxtJIroAt6vEDBK4jgbbTP3ZSGXIu7EEYzN6aE81g+fyfvqiqMu0VueUER25ghvMLr2KGbTUq7pBTnEI+pU+AeHc=,iv:wajfP/CKUvPuuHZGr9fmoWqAgp/Y2saelttVry7MMfg=,tag:qQknsIsIaMyWNR26YM1H8w==,type:str]
    OIDC_GRAFANA_CLIENT_SECRET: ENC[AES256_GCM,data:CygNcWhIZkF4l66vdRTP/wTRklnicOrXgbnEE8jamyJ6O/7ENlbMyxmu9884UUrF3bF+vG9qbP2blCKykyZSR94dNR5XZO8BuYsYyozUWeGweEllh1XuGkquVN8rdwOrzpCoUk2Haaf0bXb3pjWOilEDX8tSLBvJ5J2ILARYSPA=,iv:1udGrvbliIMug9Xp2VU7ws3PLmG8Mn/wCq4IdxQ8HTI=,tag:uLwn/limMwy4rC5ut5Kmkw==,type:str]
    #ENC[AES256_GCM,data:z2953TmO9MMJ,iv:TDn4zRrAoboor43mx2wAOhkRxZm2i/GmE6+D+5M22cE=,tag:Oa7jiNEBFX8UcrKoenAdfA==,type:comment]
    LACEWORK_TOKEN: ENC[AES256_GCM,data:9IMeNiPG334gSGKHvxgqj4c/LMieDNx4ToyJnaXgE+4bfpoMxOb6OEpQugiOi7fNGLCg0RhL3TQ=,iv:EWzSxfKMkxmJE2xIRuo46Ry6neSBzULa6eOSugMIVUE=,tag:tamykM0TsT2Nyx75a6lfAA==,type:str]
    #ENC[AES256_GCM,data:gjfqagYW5TFy,iv:HSuUWCF4HAwGQNZ19rWvho/hRGdZEbS2q6F/YLJxkiI=,tag:Oa1slaeXsXOXDDda6dBLRg==,type:comment]
    LONGHORN_BACKUP_TARGET: ENC[AES256_GCM,data:J1k+mZ/+p7Se2xJditnNhHC7z0H8cZc9blk5X+C/FV0aGUY9xUs7lU6wkA==,iv:jm/VurV9FcPKW6dWLymCCjQWeq4I68sISshxQHQx/Sk=,tag:u4cCJa75fKw2m40iDrMedQ==,type:str]
sops:
    lastmodified: "2026-02-22T22:59:53Z"
    mac: ENC[AES256_GCM,data:s7Dz8gO9q6z+lokWBrPKVU1sT4KUTq56W2W+qtVlT6DH4XoN9vHuzpwav3GJg2ovXWtnav0TLI42gqz+5k7iSv8DN2JzTqNgnUUJX8NjNMX9GJJJYggw53aTGmMamdyVFwLhBdjD9t1tYDuDud1X6rFYUgcrzvSONFeto7pQiaY=,iv:ZvPudNmk/SvlWDuXls3L8kUg23Q7aF8Iv0EGYio9epE=,tag:6MpzAZYvkfvugVuJBU6WFw==,type:str]
    pgp:
        - created_at: "2025-12-10T00:36:44Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0i7SvTnDueaAQ//bUhuOTA6VZQuCSvSBzkDl3CBtUylWCdW5ejgJ1j04W7P
            i2v5sDYyDiZwSQhRMHLAV/kEcm+yDGi/+5txPmmhNpP0u4iWXMWOhNo+02r3n4Mc
            6XbL3niisIS3aJsHIIP+I/Haz6+kAmrEbWZLRlhfPLn3KHixuTY6rlcWCFWRxDgH
            20ysx89EbkbxS+kZWeQYFTEPYtGKbTGdMzRW+/sGYXUz2C9Ayz8nvq9I6Veb5xCn
            EmziPL2WmPRytf36eVMqGzoEdAKfkn/30b/Sl6A2Yu/mqzitrbXBUuEqr8RpbT0V
            2sOgejmYrJyuwRnQjpfFd5HigZecM+3ZZuv9KJJwRtm3zA2hNpeifpDTmwnlcbcM
            EvPWXQzUXjIzFFhbLbSbSoTbhhv9zZae7VEsB7J/lkT29xzPdIe+xJ826+gCCSd+
            QLsDiFIR6Hqn9srjmXV2eKYPMeRlwvp47jjZ6lvNb+8LX1re40gp2HScmCUaGvV9
            Bxj1qihZAoLzoYwY6v9OINCZ1Zosv5C4AOXfhslp81Jd1Kjee8B6K/+vLGW5v9Hp
            z4tfeOJsP2qydsoq1ooFOUkofKWN/NJy6xf7KN7I8vMutkfckAz/x4LPFamL/Z0q
            PQX+n4o/Jctgn9EmcDQ/vV90FhMbJg9cOfsBWvIC/LjXCi4/DzQ6H8Z2nE6GSaTS
            XAH7MWdv4qiHQM1T8r2VJTe4iAk7pDaKJAo/EadmquO3TjESO70P0gnszVLL0bLx
            cDxb92kmTW3NBFk1xxeAih9hd6Krw0BjASMWHi86NOydCZRja6+ld0ntxsro
            =GE2C
            -----END PGP MESSAGE-----
          fp: 7EB1A78D86B11352982D3A1F7037153C2DB9CDBD
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
