apiVersion: v1
kind: Secret
metadata:
    name: longhorn-backup-secret
    namespace: longhorn-system
stringData:
    #ENC[AES256_GCM,data:n2KB0OAwZxP2YmfFArhnXWUxVMZgFK3DzYbIMYwRpKwLb5gosZr+8Byhg7AB,iv:VJBEDyEspJtgMcayHnT9EZr8wK3WODdFbN/64scyneg=,tag:kc8MtnF/MjpjULlemrGcFA==,type:comment]
    #ENC[AES256_GCM,data:PiMcwHZmuSPOgNi2+Aq/5u4L586SyoKgH22wLITSmRCy9asIHIIAFGDBrhwQ9CjMKU1x5MOrRCNB71u6z2Y2hQ==,iv:EkCqkWWsd9Gk15VSIOsu74OABNak/E2uIxvK9+mhAHk=,tag:H3QO7/+Q4s04Nc5jsXXpxA==,type:comment]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:bxBUJI/T97o0P9CP8fKsA6tEhtESHCt3Rw==,iv:7ZJbYXpP8KfXVl5JB7y3zFl5e086IKwigPjNdepZxbE=,tag:iYUd9sSLa7tgXu3xXYa1jQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:+CNH8guHtD6VFHrYBsLMSbcflAkU62bycbZUNhl/aA==,iv:7JuIQFfsiy7TRNkORkwl2uhj7Gxl0L4yB7VUrZdzT6Y=,tag:SYC/AitMkjtxlgHZALMusw==,type:str]
    #ENC[AES256_GCM,data:2toVOK3l37qSTPcTxUK+YiAcMcyC3gRxhS+Ovan5Dm4LTHQjang0ncztWYFFXto=,iv:pfvXoNSS+/BTuKAdXmmPjIcgf9qVO4pHNXOBroSBb70=,tag:+kck16HWbZDx52jwLoO2NA==,type:comment]
    #ENC[AES256_GCM,data:wtemjPMWq8vAta3axIGy26r8MeI6tblijCtf2BSyTQSmwUysI40rMKDeOi0=,iv:Eos4ilyA2jTo0x7HRwgzsuG+XYkXeXlr4CuSMSKFR2c=,tag:wbIgvC/ynY6J4fFYw2ix7A==,type:comment]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:5fnuwJjtH69TvSbs00w3IOeN5VlKOy6Fki7dfKxHjh5SvRD9bwU=,iv:ySSGhkzIwMasof1nUVm3HWrPKU/Aylmpxfcc8Mm36KE=,tag:3/pdSHVXFjlLvQqp0vwMzw==,type:str]
sops:
    lastmodified: "2025-12-29T00:06:27Z"
    mac: ENC[AES256_GCM,data:yRhx5kqP1HyZ9b5QBOmQ20fk25vfK42CbKyZxCfzooerA+dsB0812zHvn68i0pEM+7KOtizza3gkiV0IQcDNiGlDHkV1FX8FbmQJD6lYykGXNAHnWONhAxgut/O0RTdU4vacf2Z2WauoYOg2Ntkx/XCUpsGMXBttNTpq1YYY7nE=,iv:97pehKM949cuqsjTML8IiHW2inZSr+HjLJfpWo3oXsQ=,tag:ZKvbcEt4a2RixiNTLwAshA==,type:str]
    pgp:
        - created_at: "2025-12-29T00:04:29Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0i7SvTnDueaAQ//QitNH28PwptQS7uPjMD8pl/CGq3kfQ69xLefxaAFAZEz
            P7Z606TAtdkQJLidkVJLzTJ4ZFKNPRrHj38SE+tNAuMHcvzjnBJM/li+8dim/tMT
            QVJ/vBeytBor22tAkZd6hKEEca2j+l+IIhsAnEWhTgkruZpzHrLvkCGyvDGZdT5N
            bU0iRNF4BPhbUJmtzDYyob+KeAx5ELUUKWDr6OJ36pL/v8n5QSx+fsUxk4xA8ueg
            eNQ66NA51DLKcnS6ayaNOSkgjky4hM39vaN76GtBXNO0I10EDlYTJpTijxfCFHMI
            90OY2L9spYxGFKLgMQLJ8MrqdIFeymU3MaAnvdO7sTtMNP1Vh45Lv/wCMZ4IBhlV
            OWX2LsJPJiGrHOGK11mUgf1vDdYzkFwJKT/0QYaG/81w80hGXe0Ep4Gtq9NNqDSh
            Q1IxBw+XeqRvYJ8xWm57cPRp6tpRt67WftjEhbqfXX/CdCNz/yGP9EW3C2WwMTzV
            zuP5m5MygyjAm6zco/YwOQQwI0zpNijTCa0AVYjPua/xUXR2j5bdJ+3PtYZU5vfC
            c4OATAXQgh9FcsKyaZz6lfgT0dpsiLcdWWgP9jDhsLRioHUSbmnocvSB77aKb9H0
            qKWgrYATcrwRjHpPPMyR6HtXUbri21H0EpoagFXeBFw6ABMUog2GHZCYpdUE6onS
            XAFgxhGyN82O6jp+v0rOibVqr8rKsrODT5EKqqnPkA0czpu2DJH6T40b0AezA8Yp
            eshMpXcXTBwMWikIncsIK9TCENIUMvqtXT2piDBpFAVeTLTQywzYECrZSlDZ
            =7vI7
            -----END PGP MESSAGE-----
          fp: 7EB1A78D86B11352982D3A1F7037153C2DB9CDBD
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
