apiVersion: v1
kind: Secret
metadata:
    name: noreply-email-secrets
    namespace: default
stringData:
    #ENC[AES256_GCM,data:KMpVjScrbU06,iv:vxX8Pamjebp2hcVvz72IMLgmZzyvvZNBQ8H1zMnoEPw=,tag:pa6HDjulTttZ7GHfnf3y0w==,type:comment]
    NOREPLY_SEND_EMAIL: ENC[AES256_GCM,data:8aeUj31NmWAAwD7HsfGAo9MhE5JYjYHK,iv:MYyyVIxXhhp91BArruQUOE/PM86qwyWdb+e7T8Qccek=,tag:GLIJlgiGj7UiOSz7iuaFFw==,type:str]
    NOREPLY_AUTH_EMAIL: ENC[AES256_GCM,data:Rw3b3eTke+VTGMJg3ToHAx15xw==,iv:jE0b1nWuyZ4eKTty7mz3mmS3Yu2uQgALfr0fuj1JMeM=,tag:US9IDWV8GNvLPvaMlitDPw==,type:str]
    NOREPLY_PASSWORD: ENC[AES256_GCM,data:3upsSAVkyZ9YSkp8kXPdUx831g==,iv:l8igaon8oDQ6VOyFtGd0ZGK97CdbOtkaQTwgpCJjKSY=,tag:+QBAUbmDBADt+j3/Uj/aPg==,type:str]
sops:
    lastmodified: "2026-01-01T16:54:45Z"
    mac: ENC[AES256_GCM,data:s4vmlAT5m6pKBSWkySO7Z2siYzzbTWL1sRiouJ4sPAqbwecNWFT0BylhrLz5VYWfHDSEHNqKMTP+EKRvpeSkG3Z9M0L+DeAmUzv+sollA8YQ8EPvBf+u3iyvNaFqH4arhniRuuv4dyDPAbm6e8l+2NJ3zyv8AoaZzAz40Pjm/sc=,iv:PLOyY4/xaw1smR0Q6MQWbjNONVtvjmgHILMLbkCNM10=,tag:K74t1lx8hDCRgXEwnhT3EQ==,type:str]
    pgp:
        - created_at: "2026-01-01T16:54:45Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0i7SvTnDueaAQ//UqF5IENPso7ZO9pVwAAXnLoocKNPrh1Bh7HMz6lYsYFl
            UbDIQ4WxZJGNLWWuQghsWnla9a8PORE26c+f3V+v2WZyI5aDPYPUQw7rOrEv1VrA
            OcBpGQi9weYSeKYWKVTpeBWIcpyhyE7CFk6CRKmY7Ibun7XA5iR0n4Sg3Ea+4/14
            VIFUkuSxsZGIX8V/BJolGXpRMlyM1nxhZVWZlybJ6bgoCr7AUqNMtOrj6HH6X80n
            /fbI7C2NWripOgCJeYyxczmZ/4pIFqKjb7C4On0Mlx7J5aM8wZoUaI0N16jzasAH
            NX32YJcOFakY7OcCXVDPMK1Kv9IXr007nG45Y7YnBBrm/jWMtQzm3awbirZNWRmo
            oPCu2rnvCQdk1woXK70mUKtytPpIJL+Ir0ln/grVJESgDzEJ/2B54BLG48Ab5d3C
            gOf7d0v6prfjZTVRwlQpyy/DCSsdfEEyoAaaWGhk5UvSyTL08zd5T5SEiwiXwHOJ
            4qb7DxvGxiSoWRmssFaitIFmMrEAHNsYOmSqUfzamoOhJO8LeFWFlY93N2v0sHSS
            gltp+mIm6rvMlh6Nkl5wHztc2U0qBE/+XhmrA0lchBYVq/HVBJyzG3/xp+Tlx3OC
            fG11ou6m34f4w4Xu6TohkCekQEuyh28iXvFNVCnwsWX57lIpUeLsuTaXYkbgPOLS
            XgECwRy09sSQPNHM7D5flx0QS0mrWeMnjZbSPaVdnhRMxIKKTTpBaIszkrCnckMt
            Ep/cdNp9F9fM/g7Kf6MsTMspmjL5CUuVPI3uts32F80MucMKV7Ef5ZM51zy05ZM=
            =u9+l
            -----END PGP MESSAGE-----
          fp: 7EB1A78D86B11352982D3A1F7037153C2DB9CDBD
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
